Repository quattor/template-library-core, pull requests merged in 2018-10, with the labels that each got.

#190 test_templates: Use a single version of schema for ceph and ssh
  test_templates.sh
Labels: bug

#174 functions filesystem: partitions_add: fix number of required arguments bug
  quattor/functions/filesystem.pan
Labels: backwards incompatible

#188 Run indentation check against modified pan files
  .travis-scripts/indent
  .travis.yml
Labels: discuss at workshop
